# Board platforms lists to be used for
# TARGET_BOARD_PLATFORM specific featurization

# A Family
QCOM_BOARD_PLATFORMS += msm7x27a
QCOM_BOARD_PLATFORMS += msm7x30
QCOM_BOARD_PLATFORMS += msm8660
QCOM_BOARD_PLATFORMS += msm8960

# B Family
QCOM_BOARD_PLATFORMS += msm8226
QCOM_BOARD_PLATFORMS += msm8610
QCOM_BOARD_PLATFORMS += msm8974
QCOM_BOARD_PLATFORMS += apq8084

# B64 Family
QCOM_BOARD_PLATFORMS += msm8992
QCOM_BOARD_PLATFORMS += msm8994

# BR Family
QCOM_BOARD_PLATFORMS += msm8909
QCOM_BOARD_PLATFORMS += msm8916
QCOM_BOARD_PLATFORMS += msm8952

# UM 3.18
QCOM_BOARD_PLATFORMS += msm8937
QCOM_BOARD_PLATFORMS += msm8953
QCOM_BOARD_PLATFORMS += msm8996

# UM 4.4
QCOM_BOARD_PLATFORMS += msm8998
QCOM_BOARD_PLATFORMS += sdm660

# UM 4.9
QCOM_BOARD_PLATFORMS += sdm710
QCOM_BOARD_PLATFORMS += sdm845

# UM 4.14
QCOM_BOARD_PLATFORMS += msmnile
QCOM_BOARD_PLATFORMS += sm6150
QCOM_BOARD_PLATFORMS += trinket
QCOM_BOARD_PLATFORMS += atoll

# UM 4.19
QCOM_BOARD_PLATFORMS += kona
QCOM_BOARD_PLATFORMS += lito
QCOM_BOARD_PLATFORMS += bengal

# UM 5.4
QCOM_BOARD_PLATFORMS += lahaina
QCOM_BOARD_PLATFORMS += holi

# UM 5.10
QCOM_BOARD_PLATFORMS += taro
QCOM_BOARD_PLATFORMS += parrot

# UM 5.15
QCOM_BOARD_PLATFORMS += kalama
QCOM_BOARD_PLATFORMS += crow
